;; Blog posts index
;; Each post is an alist with metadata
;; The 'file' field should point to a markdown file in the web/blog/ directory

(
 ((slug . "whats-new-in-schematra-0-6")
  (title . "What's New in Schematra 0.6")
  (date . "2026-04-29")
  (author . "Rolando Abarca")
  (excerpt . "Webhook signature verification, Server-Sent Events, better exception reporting, and a new HTTP client backend for oauthtoothy — here's what landed in 0.5 through 0.6.")
  (image . "https://s3-us-west-1.amazonaws.com/assets.schematra.com/public/images/schematra-og.png")
  (tags . ("release" "webhooks" "sse" "testing"))
  (file . "whats-new-in-schematra-0-6.md"))
 ((slug . "building-this-blog")
  (title . "Building This Blog: A Schematra Story")
  (date . "2025-10-08")
  (author . "Rolando Abarca")
  (excerpt . "How I built this blog using Schematra, Chiccup, and lowdown - a practical example of the framework in action.")
  (image . "https://s3-us-west-1.amazonaws.com/assets.schematra.com/public/images/story-book-1.jpg")
  (tags . ("tutorial" "meta"))
  (file . "building-this-blog.md"))
 ((slug . "whats-new-in-schematra-0-4")
  (title . "What's new in Schematra 0.4")
  (date . "2025-10-27")
  (author . "Rolando Abarca")
  (excerpt . "Testing improvements, chiccup auto-rendering, and performance insights - making Schematra development smoother and faster.")
  (image . "https://s3-us-west-1.amazonaws.com/assets.schematra.com/public/images/testing-lab-04.jpg")
  (tags . ("release" "testing" "performance"))
  (file . "whats-new-in-schematra-0-4.md"))
)
